name: Manual with delay

on:
  workflow_dispatch:
    inputs:
      delay:
        description: 'Delay in seconds'
        required: true
        default: '30'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: sleep ${{ inputs.delay }}

  build2:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - run: sleep ${{ inputs.delay }}

  build3:
    runs-on: ubuntu-latest

    needs: build2

    steps:
    - run: sleep ${{ inputs.delay }}