name: Manual with delay

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: sleep 30

  build2:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - run: sleep 30

  build3:
    runs-on: ubuntu-latest

    needs: build2

    steps:
    - run: sleep 30