name: My workflow

on:
  workflow_dispatch:
    inputs:
      test:
        type: choice
        options:
          - test1
          - test2
          - test3
        description: '123'
      name:
        description: 'Name'
        required: true
        default: 'test'

jobs:
  test:
    runs-on: ubuntu-22.04

    environment: production

    if:

    steps:
    - run: echo '123'

  build:
    runs-on: debug

    needs:
    - test

    steps:
      - uses: actions/checkout@v3

      - name: Run a ${{ inputs.test }} one-line script ${{ fromJson('test') == inputs.name }}
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          'echo Add other actions to build, ${{ inputs.test == 123 }}
          echo test, and ${{ contains(inputs.name, 'test') == true }} deploy your project.'

      - name: Run a multi-line script
        run: |+
          echo Add other actions to build, ${{ inputs.test }}
          echo test, and ${{ inputs.test == null }} deploy your project.

      - name: Run a multi-line script
        run: |-
          echo Add other actions to build, ${{ inputs.test }}
          echo test, and ${{ inputs.name }} deploy your project.

      - name: Run a multi-line script
        run: >
          echo Add other actions to build, ${{ inputs.test123 }}
          echo test, and ${{ inputs.test }} deploy your project.

      - name: Run a multi-line script
        run: >+
          echo Add other actions to build, ${{ inputs.test123 }}
          echo test, and ${{ inputs.test }} deploy your project.

      - name: Run a multi-line script
        run: >-
          echo Add other actions to build, ${{ inputs.test123 }}
          echo test, and ${{ inputs.test }} deploy your project.

      - run: exit 1

      - run: echo "still running"
        if: always()
